/* Generated By:JJTree: Do not edit this line. sql\OracleParserTreeConstants.java */

package com.meidusa.amoeba.oracle.parser.sql;

public interface OracleParserTreeConstants
{
  public int JJTSTATMENT = 0;
  public int JJTVOID = 1;


  public String[] jjtNodeName = {
    "Statment",
    "void",
  };
}
