/* Generated By:JavaCC: Do not edit this line. AladdinParserTreeConstants.java Version 4.1d1 */
package com.meidusa.amoeba.aladdin.parser.sql;

public interface AladdinParserTreeConstants
{
  public int JJTSTATEMENT = 0;
  public int JJTVOID = 1;


  public String[] jjtNodeName = {
    "Statement",
    "void",
  };
}
/* JavaCC - OriginalChecksum=94462d8fd1187b16fa09ca313c48a8fc (do not edit this line) */
