/* Generated By:JJTree&JavaCC: Do not edit this line. MysqlParserConstants.java */
/*
 * Copyright (C) 2008 Struct chen <piratebase@sina.com>
 * 	This program is free software; you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, 
 * or (at your option) any later version. 
 * 
 * 	This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
 * See the GNU General Public License for more details. 
 * 	You should have received a copy of the GNU General Public License along with this program; 
 * if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package com.meidusa.amoeba.mysql.parser.sql;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MysqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_DONET = 5;
  /** RegularExpression Id. */
  int K_ALL = 6;
  /** RegularExpression Id. */
  int K_AND = 7;
  /** RegularExpression Id. */
  int K_ANY = 8;
  /** RegularExpression Id. */
  int K_AS = 9;
  /** RegularExpression Id. */
  int K_BETWEEN = 10;
  /** RegularExpression Id. */
  int K_BOOLEAN = 11;
  /** RegularExpression Id. */
  int K_BY = 12;
  /** RegularExpression Id. */
  int K_CASE = 13;
  /** RegularExpression Id. */
  int K_CAST = 14;
  /** RegularExpression Id. */
  int K_CHAR = 15;
  /** RegularExpression Id. */
  int K_CHARACTER = 16;
  /** RegularExpression Id. */
  int K_DECIMAL = 17;
  /** RegularExpression Id. */
  int K_DEC = 18;
  /** RegularExpression Id. */
  int K_DELETE = 19;
  /** RegularExpression Id. */
  int K_DISTINCT = 20;
  /** RegularExpression Id. */
  int K_DO = 21;
  /** RegularExpression Id. */
  int K_DOUBLE = 22;
  /** RegularExpression Id. */
  int K_DROP = 23;
  /** RegularExpression Id. */
  int K_ELSE = 24;
  /** RegularExpression Id. */
  int K_ELSEIF = 25;
  /** RegularExpression Id. */
  int K_END = 26;
  /** RegularExpression Id. */
  int K_ESCAPE = 27;
  /** RegularExpression Id. */
  int K_EXISTS = 28;
  /** RegularExpression Id. */
  int K_FETCH = 29;
  /** RegularExpression Id. */
  int K_FLOAT = 30;
  /** RegularExpression Id. */
  int K_FOR = 31;
  /** RegularExpression Id. */
  int K_FROM = 32;
  /** RegularExpression Id. */
  int K_FULL = 33;
  /** RegularExpression Id. */
  int K_GROUP = 34;
  /** RegularExpression Id. */
  int K_HAVING = 35;
  /** RegularExpression Id. */
  int K_IN = 36;
  /** RegularExpression Id. */
  int K_IS = 37;
  /** RegularExpression Id. */
  int K_INTO = 38;
  /** RegularExpression Id. */
  int K_INDEX = 39;
  /** RegularExpression Id. */
  int K_INNER = 40;
  /** RegularExpression Id. */
  int K_INSERT = 41;
  /** RegularExpression Id. */
  int K_REPLACE = 42;
  /** RegularExpression Id. */
  int K_INTEGER = 43;
  /** RegularExpression Id. */
  int K_INT = 44;
  /** RegularExpression Id. */
  int K_JOIN = 45;
  /** RegularExpression Id. */
  int K_LEFT = 46;
  /** RegularExpression Id. */
  int K_LIKE = 47;
  /** RegularExpression Id. */
  int K_LOCK = 48;
  /** RegularExpression Id. */
  int K_LOOP = 49;
  /** RegularExpression Id. */
  int K_CREATE = 50;
  /** RegularExpression Id. */
  int K_NOT = 51;
  /** RegularExpression Id. */
  int K_NOT2 = 52;
  /** RegularExpression Id. */
  int K_NULL = 53;
  /** RegularExpression Id. */
  int K_NULLS = 54;
  /** RegularExpression Id. */
  int K_NUMBER = 55;
  /** RegularExpression Id. */
  int K_NUMERIC = 56;
  /** RegularExpression Id. */
  int K_OF = 57;
  /** RegularExpression Id. */
  int K_ON = 58;
  /** RegularExpression Id. */
  int K_NOWAIT = 59;
  /** RegularExpression Id. */
  int K_ONLY = 60;
  /** RegularExpression Id. */
  int K_OR = 61;
  /** RegularExpression Id. */
  int K_OR2 = 62;
  /** RegularExpression Id. */
  int K_ORDER = 63;
  /** RegularExpression Id. */
  int K_OUTER = 64;
  /** RegularExpression Id. */
  int K_QUERYNO = 65;
  /** RegularExpression Id. */
  int K_OPTIMIZE = 66;
  /** RegularExpression Id. */
  int K_READ = 67;
  /** RegularExpression Id. */
  int K_REAL = 68;
  /** RegularExpression Id. */
  int K_OPTION = 69;
  /** RegularExpression Id. */
  int K_OFFSET = 70;
  /** RegularExpression Id. */
  int K_EXPLAIN = 71;
  /** RegularExpression Id. */
  int K_SELECT = 72;
  /** RegularExpression Id. */
  int K_SET = 73;
  /** RegularExpression Id. */
  int K_SOME = 74;
  /** RegularExpression Id. */
  int K_TABLE = 75;
  /** RegularExpression Id. */
  int K_SHOW = 76;
  /** RegularExpression Id. */
  int K_MOD = 77;
  /** RegularExpression Id. */
  int K_DIV = 78;
  /** RegularExpression Id. */
  int K_THEN = 79;
  /** RegularExpression Id. */
  int K_TO = 80;
  /** RegularExpression Id. */
  int K_UNION = 81;
  /** RegularExpression Id. */
  int K_UNIQUE = 82;
  /** RegularExpression Id. */
  int K_UPDATE = 83;
  /** RegularExpression Id. */
  int K_USE = 84;
  /** RegularExpression Id. */
  int K_USING = 85;
  /** RegularExpression Id. */
  int K_VALUES = 86;
  /** RegularExpression Id. */
  int K_VARCHAR2 = 87;
  /** RegularExpression Id. */
  int K_VARCHAR = 88;
  /** RegularExpression Id. */
  int K_WHEN = 89;
  /** RegularExpression Id. */
  int K_WHERE = 90;
  /** RegularExpression Id. */
  int K_WHILE = 91;
  /** RegularExpression Id. */
  int K_WITH = 92;
  /** RegularExpression Id. */
  int K_TRUE = 93;
  /** RegularExpression Id. */
  int K_FALSE = 94;
  /** RegularExpression Id. */
  int K_LIMIT = 95;
  /** RegularExpression Id. */
  int K_RIGHT = 96;
  /** RegularExpression Id. */
  int K_INTERVAL = 97;
  /** RegularExpression Id. */
  int K_YEAR = 98;
  /** RegularExpression Id. */
  int K_MICROSECOND = 99;
  /** RegularExpression Id. */
  int K_SECOND = 100;
  /** RegularExpression Id. */
  int K_DAY = 101;
  /** RegularExpression Id. */
  int K_AMOEBA = 102;
  /** RegularExpression Id. */
  int K_MINUTE = 103;
  /** RegularExpression Id. */
  int K_MONTH = 104;
  /** RegularExpression Id. */
  int K_HOUR = 105;
  /** RegularExpression Id. */
  int K_COMMIT = 106;
  /** RegularExpression Id. */
  int K_ROLLBACK = 107;
  /** RegularExpression Id. */
  int K_DESCRIBE = 108;
  /** RegularExpression Id. */
  int K_ASC = 109;
  /** RegularExpression Id. */
  int K_IGNORE_INDEX = 110;
  /** RegularExpression Id. */
  int K_FORCE_INDEX = 111;
  /** RegularExpression Id. */
  int K_TRANSACTION_ISOLATION_LEVEL = 112;
  /** RegularExpression Id. */
  int K_DUPLICATE = 113;
  /** RegularExpression Id. */
  int K_KEY = 114;
  /** RegularExpression Id. */
  int K_START_TRANSACTION = 115;
  /** RegularExpression Id. */
  int K_SESSION = 116;
  /** RegularExpression Id. */
  int K_TRANSACTION_READ_COMMITTED = 117;
  /** RegularExpression Id. */
  int K_TRANSACTION_READ_UNCOMMITTED = 118;
  /** RegularExpression Id. */
  int K_TRANSACTION_REPEATABLE_READ = 119;
  /** RegularExpression Id. */
  int K_TRANSACTION_SERIALIZABLE = 120;
  /** RegularExpression Id. */
  int K_CLIENT_CHARSET = 121;
  /** RegularExpression Id. */
  int K_SHOW_FILL_TABLES = 122;
  /** RegularExpression Id. */
  int K_SHOW_CREATE_TABLE = 123;
  /** RegularExpression Id. */
  int K_SHOW_CREATE_PROCEDURE = 124;
  /** RegularExpression Id. */
  int K_SHOW_FULL_COLUMNS = 125;
  /** RegularExpression Id. */
  int K_TABLE_STATUS = 126;
  /** RegularExpression Id. */
  int K_VARIABLES = 127;
  /** RegularExpression Id. */
  int K_GRANTS_FOR = 128;
  /** RegularExpression Id. */
  int K_TRIGGERS = 129;
  /** RegularExpression Id. */
  int K_EVENTS = 130;
  /** RegularExpression Id. */
  int K_CALL = 131;
  /** RegularExpression Id. */
  int K_CHARACTER_SET = 132;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 133;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 134;
  /** RegularExpression Id. */
  int EXPONENT = 135;
  /** RegularExpression Id. */
  int DIGIT = 136;
  /** RegularExpression Id. */
  int LINE_COMMENT = 137;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 138;
  /** RegularExpression Id. */
  int IDENTIFIER = 139;
  /** RegularExpression Id. */
  int LETTER = 140;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 141;
  /** RegularExpression Id. */
  int STRING_LITERAL = 142;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 143;
  /** RegularExpression Id. */
  int S_COMMA_IDENTIFIER = 144;
  /** RegularExpression Id. */
  int S_PARAMETER_MARKER = 145;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"@\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"AS\"",
    "\"BETWEEN\"",
    "\"BOOLEAN\"",
    "\"BY\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CHAR\"",
    "\"CHARACTER\"",
    "\"DECIMAL\"",
    "\"DEC\"",
    "\"DELETE\"",
    "\"DISTINCT\"",
    "\"DO\"",
    "\"DOUBLE\"",
    "\"DROP\"",
    "\"ELSE\"",
    "\"ELSEIF\"",
    "\"END\"",
    "\"ESCAPE\"",
    "\"EXISTS\"",
    "\"FETCH\"",
    "\"FLOAT\"",
    "\"FOR\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "\"IN\"",
    "\"IS\"",
    "\"INTO\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"INSERT\"",
    "\"REPLACE\"",
    "\"INTEGER\"",
    "\"INT\"",
    "\"JOIN\"",
    "\"LEFT\"",
    "\"LIKE\"",
    "\"LOCK\"",
    "\"LOOP\"",
    "\"CREATE\"",
    "\"NOT\"",
    "\"!\"",
    "\"NULL\"",
    "\"NULLS\"",
    "\"NUMBER\"",
    "\"NUMERIC\"",
    "\"OF\"",
    "\"ON\"",
    "\"NOWAIT\"",
    "\"ONLY\"",
    "\"OR\"",
    "\"||\"",
    "\"ORDER\"",
    "\"OUTER\"",
    "\"QUERYNO\"",
    "\"OPTIMIZE\"",
    "\"READ\"",
    "\"REAL\"",
    "\"OPTION\"",
    "\"OFFSET\"",
    "\"EXPLAIN\"",
    "\"SELECT\"",
    "\"SET\"",
    "\"SOME\"",
    "\"TABLE\"",
    "\"SHOW\"",
    "\"MOD\"",
    "\"DIV\"",
    "\"THEN\"",
    "\"TO\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UPDATE\"",
    "\"USE\"",
    "\"USING\"",
    "\"VALUES\"",
    "\"VARCHAR2\"",
    "\"VARCHAR\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "\"WHILE\"",
    "\"WITH\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"LIMIT\"",
    "\"RIGHT\"",
    "\"INTERVAL\"",
    "\"YEAR\"",
    "\"MICROSECOND\"",
    "\"SECOND\"",
    "\"DAY\"",
    "\"@amoeba\"",
    "\"MINUTE\"",
    "\"MONTH\"",
    "\"HOUR\"",
    "\"COMMIT\"",
    "\"ROLLBACK\"",
    "<K_DESCRIBE>",
    "\"asc\"",
    "\"IGNORE INDEX\"",
    "\"FORCE INDEX\"",
    "\"TRANSACTION ISOLATION LEVEL\"",
    "\"DUPLICATE\"",
    "\"KEY\"",
    "\"START TRANSACTION\"",
    "\"SESSION\"",
    "\"READ COMMITTED\"",
    "\"READ UNCOMMITTED\"",
    "\"REPEATABLE READ\"",
    "\"SERIALIZABLE\"",
    "\"CLIENT CHARSET\"",
    "<K_SHOW_FILL_TABLES>",
    "\"CREATE TABLE\"",
    "\"CREATE PROCEDURE\"",
    "<K_SHOW_FULL_COLUMNS>",
    "\"TABLE STATUS\"",
    "\"VARIABLES\"",
    "\"GRANTS FOR\"",
    "\"TRIGGERS\"",
    "\"EVENTS\"",
    "\"CALL\"",
    "\"CHARACTER SET\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<STRING_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "<S_COMMA_IDENTIFIER>",
    "<S_PARAMETER_MARKER>",
    "\"=\"",
    "\"[\"",
    "\",\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\".\"",
    "\"`\"",
    "\"!=\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"DISTINCTROW\"",
    "\"HIGH_PRIORITY\"",
    "\"STRAIGHT_JOIN\"",
    "\"SQL_SMALL_RESULT\"",
    "\"SQL_BIG_RESULT\"",
    "\"SQL_BUFFER_RESULT\"",
    "\"SQL_CACHE\"",
    "\"SQL_NO_CACHE\"",
    "\"SQL_CALC_FOUND_ROWS\"",
    "\"*\"",
    "\".*\"",
    "\"NATURAL\"",
    "\"CROSS\"",
    "\"+\"",
    "\"-\"",
    "\"|\"",
    "\"&\"",
    "\"/\"",
    "\"%\"",
    "\"DATE\"",
    "\"TIME\"",
    "\"TIMESTAMP\"",
    "\"USE INDEX\"",
  };

}
