/* Generated By:JJTree&JavaCC: Do not edit this line. MysqlParserConstants.java */
/*
 * Copyright (C) 2008 Struct chen <piratebase@sina.com>
 * 	This program is free software; you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, 
 * or (at your option) any later version. 
 * 
 * 	This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
 * See the GNU General Public License for more details. 
 * 	You should have received a copy of the GNU General Public License along with this program; 
 * if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package com.meidusa.amoeba.mysql.parser.sql;

public interface MysqlParserConstants {

  int EOF = 0;
  int K_DONET = 5;
  int K_ALL = 6;
  int K_AND = 7;
  int K_ANY = 8;
  int K_AS = 9;
  int K_BETWEEN = 10;
  int K_BOOLEAN = 11;
  int K_BY = 12;
  int K_CASE = 13;
  int K_CAST = 14;
  int K_CHAR = 15;
  int K_CHARACTER = 16;
  int K_DECIMAL = 17;
  int K_DEC = 18;
  int K_DELETE = 19;
  int K_DISTINCT = 20;
  int K_DO = 21;
  int K_DOUBLE = 22;
  int K_DROP = 23;
  int K_ELSE = 24;
  int K_ELSEIF = 25;
  int K_END = 26;
  int K_ESCAPE = 27;
  int K_EXISTS = 28;
  int K_FETCH = 29;
  int K_FLOAT = 30;
  int K_FOR = 31;
  int K_FROM = 32;
  int K_FULL = 33;
  int K_GROUP = 34;
  int K_HAVING = 35;
  int K_IF = 36;
  int K_IN = 37;
  int K_IS = 38;
  int K_INTO = 39;
  int K_INDEX = 40;
  int K_INNER = 41;
  int K_INSERT = 42;
  int K_REPLACE = 43;
  int K_INTEGER = 44;
  int K_INT = 45;
  int K_JOIN = 46;
  int K_LEFT = 47;
  int K_LIKE = 48;
  int K_LOCK = 49;
  int K_LOOP = 50;
  int K_CREATE = 51;
  int K_NOT = 52;
  int K_NULL = 53;
  int K_NULLS = 54;
  int K_NUMBER = 55;
  int K_NUMERIC = 56;
  int K_OF = 57;
  int K_ON = 58;
  int K_NOWAIT = 59;
  int K_ONLY = 60;
  int K_OR = 61;
  int K_ORDER = 62;
  int K_OUTER = 63;
  int K_QUERYNO = 64;
  int K_OPTIMIZE = 65;
  int K_READ = 66;
  int K_REAL = 67;
  int K_OPTION = 68;
  int K_SELECT = 69;
  int K_SET = 70;
  int K_SOME = 71;
  int K_TABLE = 72;
  int K_SHOW = 73;
  int K_MOD = 74;
  int K_DIV = 75;
  int K_THEN = 76;
  int K_TO = 77;
  int K_UNION = 78;
  int K_UNIQUE = 79;
  int K_UPDATE = 80;
  int K_USE = 81;
  int K_USING = 82;
  int K_VALUES = 83;
  int K_VARCHAR2 = 84;
  int K_VARCHAR = 85;
  int K_WHEN = 86;
  int K_WHERE = 87;
  int K_WHILE = 88;
  int K_WITH = 89;
  int K_TRUE = 90;
  int K_FALSE = 91;
  int K_LIMIT = 92;
  int K_RIGHT = 93;
  int K_INTERVAL = 94;
  int K_YEAR = 95;
  int K_MICROSECOND = 96;
  int K_SECOND = 97;
  int K_DAY = 98;
  int K_MINUTE = 99;
  int K_MONTH = 100;
  int K_HOUR = 101;
  int K_COMMIT = 102;
  int K_ROLLBACK = 103;
  int K_TRANSACTION_ISOLATION_LEVEL = 104;
  int K_START_TRANSACTION = 105;
  int K_SESSION = 106;
  int K_TRANSACTION_READ_COMMITTED = 107;
  int K_TRANSACTION_READ_UNCOMMITTED = 108;
  int K_TRANSACTION_REPEATABLE_READ = 109;
  int K_TRANSACTION_SERIALIZABLE = 110;
  int K_CLIENT_CHARSET = 111;
  int INTEGER_LITERAL = 112;
  int FLOATING_POINT_LITERAL = 113;
  int EXPONENT = 114;
  int DIGIT = 115;
  int LINE_COMMENT = 116;
  int MULTI_LINE_COMMENT = 117;
  int IDENTIFIER = 118;
  int LETTER = 119;
  int SPECIAL_CHARS = 120;
  int STRING_LITERAL = 121;
  int S_QUOTED_IDENTIFIER = 122;
  int S_COMMA_IDENTIFIER = 123;
  int S_PARAMETER_MARKER = 124;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"@\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"AS\"",
    "\"BETWEEN\"",
    "\"BOOLEAN\"",
    "\"BY\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CHAR\"",
    "\"CHARACTER\"",
    "\"DECIMAL\"",
    "\"DEC\"",
    "\"DELETE\"",
    "\"DISTINCT\"",
    "\"DO\"",
    "\"DOUBLE\"",
    "\"DROP\"",
    "\"ELSE\"",
    "\"ELSEIF\"",
    "\"END\"",
    "\"ESCAPE\"",
    "\"EXISTS\"",
    "\"FETCH\"",
    "\"FLOAT\"",
    "\"FOR\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "\"IF\"",
    "\"IN\"",
    "\"IS\"",
    "\"INTO\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"INSERT\"",
    "\"REPLACE\"",
    "\"INTEGER\"",
    "\"INT\"",
    "\"JOIN\"",
    "\"LEFT\"",
    "\"LIKE\"",
    "\"LOCK\"",
    "\"LOOP\"",
    "\"CREATE\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"NULLS\"",
    "\"NUMBER\"",
    "\"NUMERIC\"",
    "\"OF\"",
    "\"ON\"",
    "\"NOWAIT\"",
    "\"ONLY\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"OUTER\"",
    "\"QUERYNO\"",
    "\"OPTIMIZE\"",
    "\"READ\"",
    "\"REAL\"",
    "\"OPTION\"",
    "\"SELECT\"",
    "\"SET\"",
    "\"SOME\"",
    "\"TABLE\"",
    "\"SHOW\"",
    "\"MOD\"",
    "\"DIV\"",
    "\"THEN\"",
    "\"TO\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UPDATE\"",
    "\"USE\"",
    "\"USING\"",
    "\"VALUES\"",
    "\"VARCHAR2\"",
    "\"VARCHAR\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "\"WHILE\"",
    "\"WITH\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"LIMIT\"",
    "\"RIGHT\"",
    "\"INTERVAL\"",
    "\"YEAR\"",
    "\"MICROSECOND\"",
    "\"SECOND\"",
    "\"DAY\"",
    "\"MINUTE\"",
    "\"MONTH\"",
    "\"HOUR\"",
    "\"COMMIT\"",
    "\"ROLLBACK\"",
    "\"TRANSACTION ISOLATION LEVEL\"",
    "\"START TRANSACTION\"",
    "\"SESSION\"",
    "\"READ COMMITTED\"",
    "\"READ UNCOMMITTED\"",
    "\"REPEATABLE READ\"",
    "\"SERIALIZABLE\"",
    "\"CLIENT CHARSET\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<STRING_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "<S_COMMA_IDENTIFIER>",
    "\"?\"",
    "\";\"",
    "\".\"",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"!=\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"DISTINCTROW\"",
    "\"HIGH_PRIORITY\"",
    "\"STRAIGHT_JOIN\"",
    "\"SQL_SMALL_RESULT\"",
    "\"SQL_BIG_RESULT\"",
    "\"SQL_BUFFER_RESULT\"",
    "\"SQL_CACHE\"",
    "\"SQL_NO_CACHE\"",
    "\"SQL_CALC_FOUND_ROWS\"",
    "\"*\"",
    "\".*\"",
    "\"NATURAL\"",
    "\"CROSS\"",
    "\"+\"",
    "\"-\"",
    "\"||\"",
    "\"/\"",
    "\"%\"",
    "\"DATE\"",
    "\"TIME\"",
    "\"TIMESTAMP\"",
  };

}
