/* Generated By:JJTree: Do not edit this line. sql\AladdinParserTreeConstants.java */

package com.meidusa.amoeba.aladdin.parser.sql;

public interface AladdinParserTreeConstants
{
  public int JJTSTATMENT = 0;
  public int JJTVOID = 1;


  public String[] jjtNodeName = {
    "Statment",
    "void",
  };
}
