/* Generated By:JJTree: Do not edit this line. sql\MysqlParserTreeConstants.java */

package com.meidusa.amoeba.mysql.parser.sql;

public interface MysqlParserTreeConstants
{
  public int JJTVOID = 0;


  public String[] jjtNodeName = {
    "void",
  };
}
