/* Generated By:JavaCC: Do not edit this line. AladdinParserTreeConstants.java Version 4.1d1 */
package com.meidusa.amoeba.aladdin.parser.sql;

public interface AladdinParserTreeConstants
{
  public int JJTSTATMENT = 0;
  public int JJTVOID = 1;


  public String[] jjtNodeName = {
    "Statment",
    "void",
  };
}
/* JavaCC - OriginalChecksum=633191f82f099a9499d26944541c145e (do not edit this line) */
